client/src/api/api.js
src/routes/v1/apps/handlers/editImage.js
src/server/init-server.js

After upgrading hapi, something about how it handles `content-type` has changed, resulting in PUT-requests failing since they were sending the JSON as `text/plain`. The error was due to sending a JSON-stringified object to Joi-validation. Before it seems that hapi would be able to parse this into `request.payload` automatically, but not always? It's weird, as some endpoints (`/editAppVersions`, `/editApp`) did not need to parse the payload, but `/editImage` did? ~~I don't really understand why. Any ideas @erikarenhill ?~~
Either way I feel that it's a good thing that the error was caught, as it shouldn't really have worked before.
**EDIT**: I figured out why: `joi@16` is no longer automatically converting strings to object or arrays, see "Array and object string coercion" in the release …

fix: contentype to json

---

seeds/06_media.js
src/data/addAppVersionMedia.js
src/models/v1/in/CreateAppModel.js
src/routes/v1/apps/handlers/createApp.js
test/data/index.js

Currently the information about the image uploaded together with the app was ignored. This adds support to add caption and description when creating a new app.

fix: save logo caption and description when uploading app

---

test/routes/index.js

Since we broke swagger docs/generation without noticing, I just added simple smoke tests for this. (swagger.json still returns http 500 but at least now we know and get the status with builds...)

test: make sure swagger endpoints respond with http status 200

---

buildspec.yml

Idea is to build the client app in the build pipeline, and then pack it with the source (we need to ignore node_modules for now so removing it before creating the archive).
This will be passed on to the EBS deploy, which will run `npm install` to get the runtime deps needed for the server, and then start everything up.
First step to see if this works is to add the `USE_PREBUILT_APP` environment variable to our staging environments.
If everything works and it stops "broken" deploys, then we can remove the internal compilation mechanism completely.

ci(codebuild): create artifact containing the built app and server src

---

src/plugins/apiRoutes.js
src/plugins/staticFrontendRoutes.js
src/server/init-server.js

To get better separation in the code, and also isolating the hapi server context between static and api routes this PR moves them into separate plugins to clean up a bit and hopefully work better

refactor: separate static/api to hapi plugins

---

src/plugins/apiRoutes.js

without this fix, it will not be able to start the server running without authentication when debug as undefined will be used

fix: require debug thats missing since refactor

---

src/routes/v1/apps/formatting/convertAppsToApiV1Format.js
src/utils/getServerUrl.js
src/utils/index.js
test/utils/index.js

Since the nginx reverse proxy in AWS EBS in front of our hapijs/nodejs backend does ssl termination the backend will return http-links even when doing requests over https. To resolve this we pick up the forwarded protocol, port and hostname if available.
According to this docs: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html the headers is added by default, otherwise we can override the nginx config with a custom ebextension/nginx/nginx.conf file.

fix: make backend use correct urls behind proxy

---

src/routes/v2/channels.js
test/routes/v2/channels.js

Api endpoint for creating/adding new channels to the database. Requires authorization corresponding to a logged in manager (or running backend without auth enabled)

feat: create/post channel api endpoint

---

package-lock.json
package.json

deploy failed since semver was added incorrectly added as a devdependency, this moves it to dependencies

chore: move semver from devdeps

---

client/src/api/api.js
client/src/components/appCards/AppCards.jsx
client/src/components/appVersion/VersionListEdit.jsx
client/src/components/form/NewAppVersionForm.jsx
client/src/components/form/UploadAppFormStepper.jsx
client/src/reducers/channelReducer.js
default.config.js
development.config.js
src/data/createAppVersion.js
src/models/v1/in/CreateAppVersionModel.js
src/routes/v1/apps/handlers/createAppVersion.js

Previously the appstore frontend had a static config for release channels, now they are being loaded dynamically from the backend instead. This PR also contains a few bug fixes regarding channels when editing/creating versions and uploading new apps.

feat: load channels from backend

---

client/src/components/appVersion/VersionListEdit.jsx
src/data/deleteAppVersion.js
src/data/index.js
src/routes/v1/apps/handlers/deleteAppVersion.js
src/routes/v1/apps/index.js

This PR adds functionality in the new backend to delete a specific app version
It also tweaks the padding of the version list table to make for example the trash-icon visible again instead of hidden due to overflow when editing the app
We might want to double check that relational data gets deleted in the db as well when removing a row in the app_version table
* fixes DHIS2-7846
TODO: tests

feat: add possibility to delete an app version

---

client/src/components/appCards/AppCards.jsx
client/src/components/utils/Filters.jsx
client/src/reducers/formReducer.js
client/src/utils/history.js

The changes in this PR makes the channel and appType filter to stick in the redux store form section which makes it possible for the user to change filters, click into an application detail, then back without having the filters being reset to only display Stable again

fix: keep filters in redux form state when navigating around

---

src/plugins/apiRoutes.js
src/server/init-server.js

We should not change the server.realm object, as per the [documentation](https://hapi.dev/api/?v=18.4.0#-serverrealm): 
> The server.realm object should be considered read-only and must not be changed directly except for the plugins property which can be directly manipulated by each plugin, setting its properties inside plugins[name].

fix: add route prefix the correct way

---

src/models/v2/Default.js
src/models/v2/Organisation.js
src/models/v2/User.js
src/routes/v2/index.js
src/routes/v2/organisations.js
src/services/index.js
src/services/organisation.js
src/utils/databaseUtils.js
src/utils/errors.js
test/routes/v2/organisations.js
test/services/organisation.js

I've been deep down a rabbit hole of trying out multiple approaches to how to deal with database-results etc. My original branch was starting to get quite far behind, with a lot of random commits that does not make sense anymore, so the result is that I brought some of the ideas to this branch, and if we like it I can introduce the other stuff as well (eg. filtering and paging).
This touches on most of the keypoints in the [issue](#139) raised earlier. I will try to tackle the keypoints and explain my thoughts.
We didn't want an ORM and that's fine. However I found using the raw database results very cumbersome. "Service" is a very imprecise term, but it's what I came to call this, but they are not classes or injected in any way - they are simple functions exported together. I'm not …

feat: organisation services

---

src/plugins/apiRoutes.js

Plugins should not call System.exit(). When running tests without `NO_AUTH_MAPPED_USER_ID` I did not get an error, the tests just exit as debug are not shown in tests, which was very confusing. To me it makes much more sense to throw an error here, which also crashes the app.

fix: throw error from apiPlugin instead of exit

---

Dockerfile
src/server/compile-webapp.js

This Dockerfile provides support for setting up an apphub instance without the database (using the env vars passed in for database). 
I will also providing the entire "apphub-cluster" within the docker-compose repository to spin up a postgres database along with the nodejs backend/frontend setup.
When this is merged I'd be happy to get some help setting up the auto-deploy/build stuff to automatically push the docker image to our registry

feat: add support for using docker

---

Dockerfile
package.json

By using a multi-stage build to separate the build and serve phases, and
attempt to only include what we need to run in the serve phase, we can
cut down the image from 1.2 GB to 570 MB (unpacked).
Once we are using workspaces in this repo, we can further improve this
situation by separating the deps for the client and for the server. As
the client is precompiled the deps are included in the bundle, but now
they are listed in the dependencies array in package.json which means
the server will install them even when they aren't necessary.

ci(docker): trim the docker image size

---

src/routes/v1/apps/handlers/getAllApprovedApps.js
test/routes/index.js

this is to match whats being used in the app management app

fix: rename version filter querystring param

---

client/src/components/form/NewAppVersionForm.jsx

add required form validation to "create new version" - to not crash when trying to submit with incorrect values in the POST to the backend

fix: add required validation to NewAppVersion form

---

server/src/routes/v1/apps/handlers/deleteApp.js
server/test/routes/deleteApp.js
tools/clean.js
tools/env.template

Incorrect id was used when deleting the directory where the app is stored, making the api request when deleting an app to fail

fix: make delete app work properly

---

migrations/20200203182043_fix_view_users_with_organisations.js

Small fix for the view. The view is not used by anything yet, but is handy to have.
I believe it's fine to update migrations directly like this when it's a bug-fix right?

fix: users-with-organisation view

---

client/src/components/appVersion/VersionListEdit.jsx
server/seeds/01_organisation-developers.js
server/seeds/mock/users.js
server/src/data/getOrganisationAppsByUserId.js
server/src/data/index.js
server/src/routes/v1/apps/handlers/createAppVersion.js
server/src/routes/v1/apps/handlers/editApp.js
server/src/routes/v1/apps/handlers/editAppVersion.js
server/src/routes/v1/apps/handlers/getAppFile.js
server/src/routes/v1/apps/handlers/getMyApps.js
server/src/routes/v1/apps/handlers/getSingleApp.js
server/src/routes/v2/organisations.js
server/src/security/index.js
server/test/routes/v2/organisations.js
server/test/services/organisation.js

this adds possibility to authenticate the user on the download endpoint for apps, and passes the JWT-token in the querystring on download links when viewing an unapproved/rejected app in the admin/edit-version of the gui.
This also brings in some changes to how a developer is determined to have access to an app. Previously it would only allow edit-access if being the developer that uploaded the app, now it will allow access to all apps which you belong to the same organisation it's connected to.
Also tested that you can retreive "myapps" with a user having multiple organisations
Adds transaction/rollback beforeEach/afterEach organisation unit tests

fix: allow admins to download all apps

---

server/src/routes/v1/apps/handlers/createApp.js

We need to add the current user to the created organisation, or else the uploading user won't have access to the newly created app.

fix(createapp): add user to organisation if org does note xist

---

client/src/components/appCards/AppCardItem.jsx

After the introduction of the div with `data-test` attribute, the appcards did not have the same height in certain viewport widths.

fix: appcard height

---

client/default.config.js
client/development.config.js
client/src/actions/epics.js
client/test/config/configResolver.spec.js
server/src/data/index.js
server/src/models/v1/in/CreateAppModel.js
server/src/routes/v1/apps/handlers/createApp.js
server/src/routes/v1/apps/handlers/editApp.js
server/src/services/organisation.js
tools/clone.js
tools/helpers/downloadImages.js
tools/helpers/getAuthToken.js

Note that this builds upon #310 , so that should probably be merged first.
To keep access for the uploading user we need to add that user to the organisation the app is uploaded to. The developer-user and owner may be completely different emails/users. Normally, when uploading an app, the user uploading the app are the owner, and thus added to that organisation (fixed in #314 ). However when uploading apps with the clone script, the M2M user will be the current user, and therefore the user that uploaded the app in the previous appstore won't have access unless the developer email is the same.
The fix is not pretty to be honest. I've modified the v1 API, but this is not breaking as it just adds a new object that can be attached to the app. This object describes the owner of the app, so it …

fix(clone): keep owner access

---

server/src/data/deleteAppMedia.js
server/src/data/index.js
server/src/routes/v1/apps/handlers/createApp.js
server/src/routes/v1/apps/handlers/deleteImage.js

Fixes upload of logo and deletion of logo introduced in #285 .
When uploading a logo the logo was saved with `media_id` instead of `app_media_id`. The app is given `app_media_id` for the ID of images so the `getAppMedia`-endpoint would return 404 since it tried to get the image by the `app_media_id` these IDs are obviously different.
The same was kind of true for deletion of media. The naming of IDs was very confusing here, as it tried to get the `media_id` using the `mediaId`. However, it also deleted from `media`-table instead of `app_media`-table - which does not have cascading.
The result is that we're now saving images with `app_media_id` instead of `media_id`. I'm unsure of the original thought behind this and which IDs we should expose in the API and which we should use when saving …

fix: upload and deletion of logo

---

server/src/routes/v1/apps/formatting/convertAppsToApiV1Format.js
server/src/routes/v1/apps/handlers/getAppFile.js
server/test/routes/index.js

should resolve https://jira.dhis2.org/browse/DHIS2-9256 if the backend makes use of the content-disposition filename from header

fix: use slug + version as filename on download

---

server/src/routes/v1/apps/handlers/deleteAppVersion.js
server/src/routes/v1/apps/handlers/deleteImage.js
server/src/routes/v1/apps/handlers/uploadImageToApp.js

previously a developer (non manager) could not delete an app-version, upload image, or delete an image on his own apps after it was created the first time. This PR fixes all those
https://jira.dhis2.org/browse/HUB-84
https://jira.dhis2.org/browse/HUB-85
https://jira.dhis2.org/browse/HUB-86

fix: verify developer permission correctly on several API endpoints

---

server/src/plugins/apiRoutes.js

Adds a catch-all route for `/api` that returns the default `404-error`. Previously the  catch-all route in staticFrontendRoutes would also catch 404 under `/api`, and return `index.html`. 
http://localhost:3000/api/appz -> would previously return `index.html`. Now it returns 404.

fix(apiroutes): add 404-handler for /api

---

server/migrations/20200924140557_version-replace-underscore.js
server/src/models/v1/in/CreateAppModel.js
server/src/models/v1/in/EditAppVersionModel.js
server/src/routes/v1/apps/formatting/convertAppsToApiV1Format.js
server/src/routes/v1/apps/handlers/getAppFile.js

Using `_` in the app-version causes problems as `_` is used to separate the app-slug and the version. Underscores are not encoded by `encodeURIComponent`, so using that will not prevent the invalid URL. 
I've added a migration that replaces all versions with `_` to be replaced with `.`. I've also added validation to the server to prevent versions containing `_`. However we probably should have some more validation to enforce versioning best-practices. Any input on that? We could use `semver` to validate versions, and we do not necessarily need to apply that retroactively.

fix(download): encode download-components, forbid _ in version

---

client/src/api/utils.js

Seems like staging and prod are using `/api/` as the baseUrl, and as we removed both trailing and leading slashes that was treated as a relative url, so apiv2 requests resolved to `/user/api` in some cases. With the leading `/` fetch will resolve to the domain-root.

fix(api): fix apiV2 apiUrl

---

client/src/components/dialog/DialogBase.js
client/src/components/dialog/EditAppVersionDialog.js
client/src/components/dialog/NewAppVersionDialog.js
client/src/components/form/AppVersionForm.jsx

Some of the dialogs has a loading indicator which affects the height of the dialog-content significantly. These dialogs needs a min-height for the Dialog-position calculation to be correct.
Calculation is also improved when loading channels for the second time, as we already have the channels, so we just render these and don't block the UI with a spinner. Channels will probably never change in a session regardless.

fix(dialog): dialog position

---

README.md
package.json
server/.env.template
server/package.json

To simplify local installation, I've moved some tasks (such as creating database tables and seeding them) to `package.json` scripts and have updated the README accordingly.
I've also moved the backend configuration documentation to `.env.template`.

fix: improve README instructions for local installation

---

server/migrations/20210209171106_api-key.js
server/package.json
server/src/plugins/apiRoutes.js
server/src/routes/v2/apikey.js
server/src/routes/v2/index.js
server/src/security/apiKeyScheme.js
server/src/security/createApiKeyValidationFunc.js
server/src/security/index.js
server/src/services/apiKey.js
server/src/services/index.js
server/test/routes/v2/apiKey.js
server/test/security/apiKeyScheme.js
server/test/services/apiKey.js

This implements an API to generate API-keys. The generated API-key can be used instead of an OAuth token to identify the request from the user, provided in the `x-api-key`-header in the request. 
See https://jira.dhis2.org/projects/HUB/issues/HUB-100 for more information about the considered implementation options. I decided to generate the key using uuid-v4 and hashing this with sha-256. This was the simplest solution; we already have uuid-v4 as a dependency, it's cryptographically secure (backed by [crypto.randomFill](https://nodejs.org/api/crypto.html#crypto_crypto_randomfill_buffer_offset_size_callback)), it's fast and we do not need secrets. However it means that the user cannot see the API-key after first generation. However it's simple to revoke and generate a new one.
Note that …

feat: apiKey generation

---

server/src/models/v1/in/CreateAppVersionModel.js
server/src/routes/v1/apps/handlers/createAppVersion.js

Adds support for uploading app-version with api-key. 
There was a few bugs when testing this due to not actually using the transaction in the helper-function to create the version. This resulted in partially DB-creations. Eg. if you tried to upload with an invalid channel, the version was created in the `app_version`-table, but it failed later when trying to add the version to the channel-table. This resulted in a 500-error if you tried to upload the version again (with fixed channel), even though the version would not show up in the API. 
I intend to merge this using regular merge as the commits are standalone. They are related but does not depend on each other.

fix(version): fix app version upload

---

client/src/components/apps/Apps.jsx
client/src/components/apps/Filters.jsx

Filtering apps using a search query, clicking on an app and then returning to the previous page results in a blank searchbox even though the URL query params contains the correct query.
This PR fixes this issue by passing the query value on first render to the search filter.

fix: show query in input when returning from search result

---

server/src/utils/filters.js

These lines made it really difficult to read the logs, as it was spammed for each version whenever the a user loaded the index page.
Don' think these give value information anyway, and should've been deleted after implementation.

fix: remove debug lines that spam logs

---

server/src/utils/slugify.js
server/test/data/index.js
server/test/routes/index.js

In order to aid decoding, `punycode` appends a hyphen to the end of encoded strings. As we do not need to decode our slugs, using `toASCII` fits our use case better.

fix: use punycode.toASCII instead of punycode.encode

---

server/src/routes/v2/version.js

`Dockerfile` does not seem to include the root-workspace `package.json`, so lets use the `server`-one instead.

fix(version-api): use server-package.json for version information

---

server/src/routes/v1/apps/handlers/createApp.js
server/src/routes/v1/apps/handlers/createAppVersion.js

If a user attempts to upload a new app with incorrect metadata, they currently encounter the error message 'internal service error' instead of the more informative message provided by `verifyBundle`.

feat: more informative user-facing errors regarding metadata verification

---

server/src/security/verifyBundle.js

See https://jira.dhis2.org/browse/HUB-123
The check might look a bit weird, but I did not want to introduce a requirement for `manifest.appType`, even though it should be in the manifest. It's either that or a check like `if (manifest.name !== appName) && !manifest.appType || (manifest.appType && manifest.appType !== 'DASHBOARD_WIDGET')`. If you have a better solution please give feedback.

fix(verifybundle): ignore name-check for dashboard_widget

---

client/src/pages/AppView/AppView.js
client/src/pages/AppView/AppView.module.css
client/src/pages/Apps/AppCards/AppCardItem/AppCardItem.js
client/src/pages/Apps/AppCards/AppCardItem/AppCardItem.module.css
client/src/pages/Apps/AppCards/AppCards.js
client/src/pages/UserApp/DetailsCard/DetailsCard.js
client/src/pages/UserApp/DetailsCard/DetailsCard.module.css
client/src/pages/UserAppEdit/UserAppEdit.js
server/migrations/20210705145813_core-app.js
server/src/data/createApp.js
server/src/data/getApps.js
server/src/data/updateApp.js
server/src/models/v1/in/CreateAppModel.js
server/src/models/v1/in/EditAppModel.js
server/src/models/v1/out/App.js
server/src/models/v2/in/CreateAppModel.js
server/src/routes/v1/apps/formatting/convertAppsToApiV1Format.js
server/src/routes/v1/apps/handlers/createApp.js
server/src/routes/v1/apps/handlers/editApp.js
server/src/security/verifyBundle.js
server/src/services/app.js

Adds a property for identifying a core app.
The `core_app`-field is read from the manifest and set if it is true. In that sense this is the first information we are automatically getting from the manifest/d2.config. Note that the uploader must be a manager to be able to set this. 
I've also implemented a simple override for this when editing an application. And you have to be a manager for this property-change to have an effect. 
I'm a bit unsure about how we should show this to users, currently I have a simple tag for this:
Could potentially have the DHIS2 logo instead? Feedback welcome.

feat: add coreApp property

---

server/src/models/v2/AppVersion.js
server/src/plugins/pagination.js
server/src/plugins/queryFilter.js
server/src/query/Pager.js
server/src/query/executeQuery.js
server/src/routes/v1/apps/handlers/editApp.js
server/src/routes/v2/appVersions.js
server/src/routes/v2/apps.js
server/src/routes/v2/index.js
server/src/server/init-server.js
server/src/services/appVersion.js
server/src/utils/Filter.js
server/src/utils/filterUtils.js
server/test/routes/v2/appVersions.js

Implements an AppVersions API that can be used to paginate and filter versions of an app.
This uses the new architecture, and takes full advantage of the queryFilter-plugin and pagination plugin, as well as the `executeQuery`-abstraction. 
Appversion is implemented as a Schmervice service. This is not strictly necessary as we do not have state or initialization. But I do like the approach, and it makes implementing caching pretty trivial if that is needed down the line.

feat: AppVersion API

---

server/src/models/v2/AppVersion.js
server/src/routes/v2/appVersions.js

I mistakenly did not include the rename-model for the queryFilter. The renames in the sql-query in the service (with `.as()`) is only applied to the results, we also need to rename the query-filter keys to the matching DB-column.
Eg. `minDhisVersion` to `min_dhis2_version`.

fix(appversion): add renames for query-filters

---

server/src/query/Pager.js
server/src/query/executeQuery.js
server/test/data/index.js
server/test/query/executeQuery.js
server/test/routes/v2/appVersions.js

In the first iteration of pagination we used the window function `over()`, to do a somewhat performant and simple way to grab the total number of results in a query (before limit is applied). However this does not support `distinct`, which is needed in a `AppVersion` query. So whenever a `distinct` is used in a query, and whenever there are duplicate tuples, the total will be more than what we actually want.
In this PR I've switched out the window-function with a separate total-count query. In the initial implementation I argued against this due to performance reasons. But due to the constraints above, I've decided to implement it with a separate query, as it's much more flexible (which is how DHIS2 handles `total` as well). There's some performance issues with `total` in DHIS2, but that …

fix(pagination): separate total count query

---

client/src/pages/AppView/AppView.js
client/src/pages/Apps/AppCards/AppCardItem/AppCardItem.js
client/src/pages/Apps/AppCards/AppCards.js
client/src/pages/UserApp/DetailsCard/DetailsCard.js

This was added in https://github.com/dhis2/app-hub/pull/522 , but in a recent meeting (Sept 13.) we discussed moving away from the term "core apps" as it's quite ambiguous. Improving upon the organisation feature with a page for organisation should help featuring DHIS2 apps.

fix: remove core app tag

---

server/seeds/04_appchannel.js
server/src/services/appVersion.js
server/src/utils/Filter.js
server/src/utils/filterUtils.js
server/test/data/index.js
server/test/routes/v2/appVersions.js

We allow null and empty strings for `maxDhisVersion`, and the previous filtering implementation would just do a naive `where`, so it would not return any results.
This implements a generic way to include "empty" results for a filter through an option `includeEmpty` to `applyOneToQuery`. Empty is defined as `null`, the empty string `''` or a string with just spaces.
Implements a simple way to compare version numbers in SQL. Note that this is not fully `semver` compatible, as it only supports simple  version-numbers (no prelease, beta, etc), however that should be fine for now as we only use it for DHIS core version. There is a [semver postgres-plugin](https://pgxn.org/dist/semver/), but that is more work to implement. 
Also includes `gte` (greater or equal) to the list of allowed operators …

fix(appversion): fix version filtering

---

server/src/routes/v2/apps.js
server/src/services/appVersion.js
server/test/routes/v2/appVersions.js
server/test/routes/v2/apps.js

Adds a simple API-endpoint that fetches all channels that have a published version for a particular app.
The purpose for this API is for the client to know which 'channel'-filters to show, as we want to hide channels that are not relevant for that app. This was previously done on the client side, but this endpoint is needed to support this feature when we are moving to paginated responses (#555 ).
`/v2/apps/APPID/channels`

feat(apps): availableChannels API

---

server/src/query/Pager.js
server/src/query/executeQuery.js
server/src/services/appVersion.js
server/test/query/executeQuery.js

In https://github.com/dhis2/app-hub/pull/543 we moved to a separate query to get the total-count. This was mainly due to usecases that used `distinct`. However this was solved by modifying the `appVersion`-query to not need `distinct`. 
Even though the performance seem to not really be measurable (locally it\s below 10 ms), the latency from our server to RDS is bigger than that. Even though it is fine for now, it is an unnecessary default and I've implemented a way for each query to be able to specify their strategy, according to the needs of that particular query. The default is back to use `count() over()`, a window function that uses the entire result set (even in case of offsets). We still have to count all tuples, but it's done in one query now.
These options are available:
- …

feat: configurable total-results strategy

---

client/src/pages/UserOrganisation/Modals/EditNameModal.js
server/src/routes/v2/organisations.js
server/src/services/organisation.js

A few bugs made saving the email of the organisation not work at all.
Seems like after the UI refactor, the email field for editing the org-email was not included in the modal.
Also, the route-handler did not pass the email-param to the service when creating an org.
The result was that both these bugs made it virtually  impossible to actually save the email of an organisation.

fix: save org-email

---

server/seeds/04_appchannel.js
server/seeds/mock/appversions.js
server/seeds/mock/appversions_localized.js
server/src/utils/Filter.js
server/test/routes/v2/appVersions.js

Empty `maxDhisVersion` (`''`) should now properly be included when filtering on `maxDhisVersion`.
This was probably not caught due to me reading somewhere that `nullif('', ' ')` should return true (with any blank string), but that is not the case in postgres- which makes sense. And most tests used `lte`, which included the empty-string regardless of the `or nullif`-case. 
Also added some more tests and related seeds.
On a slightly related note, we should've some better constraints/checks for `maxDhisVersion` and `minDhisVersion`, as currently they allow anything to be stored. At least we should protect against this in the application-layer/Joi-validation.

fix(filter): properly include version if maxDhisVersion is empty

---

client/src/components/Header/Header.js

Hide apps-menu in header bar when not logged in.
Also renames "Your apps" to "My apps", and other related menu-items, as suggested by @germanviscuso .

fix: hide apps in header-menu when not logged in

---

client/src/pages/UserApp/DetailsCard/DetailsCard.js
client/src/pages/UserApp/ScreenshotsCard/UploadScreenshot.js
client/src/pages/UserAppUpload/UserAppUpload.js
server/src/utils/validateMime.js

- Sets the accepted filetypes for various `<input type="file">` inputs used across the app for image uploads to `image/jpeg,image/png`.
- Improves the error message shown to users when an attempt at uploading an invalid image file is made

fix: improve UX of invalid image filetype errors

---

client/src/pages/UserAppUpload/UserAppUpload.js

This is untested but should work. The instructions for locally installing the app hub are very clear, but it seemed like quite a bit of work to do for a one-line fix.

fix(add app): allow clearing optional select field

---

server/src/routes/v1/apps/formatting/convertAppsToApiV1Format.js

Fixes `sourceUrl` being cleared in the UI when a new version is uploaded. This is done by making sure any app-version sourceUrl is used, not just the first being "collected". This is the easiest fix that I could come up with that does not need to run any migration to populate missing sourceUrls.
The reason for this is that `source_url` is in the `app_version`-table. It really should be in the "app"-table, because we should not have different `source_url`s for each version. I guess this was done in good spirit, making it possible to "migrate" source to another repository host between versions - but it's such an obscure use-case and results in tons of duplicated data.
I've not done any database fixes, because that is much more work and quite risky. I think we can do that once we introduce a …

fix(apps): fix sourceUrl being cleared when version is uploaded

---

client/src/pages/AppView/AppView.js
client/src/pages/AppView/AppView.module.css

**Before**
**After**
I removed the max-width on the text because it seems like it will not overflow the button length that much in most cases (and the button width would be language dependent if we internationalized in the future). If we keep the max-width, the second sentence in this example `Compatible with DHIS2 3.33 and above.` would have been on two lines, which I thought  looked a bit odder.

fix: break version sentences [HUB-150]

---

server/src/models/v2/AppVersion.js
server/src/query/executeQuery.js
server/src/routes/v2/appVersions.js
server/src/services/appVersion.js
server/test/routes/v2/appVersions.js

#661 grew a bit out of scope, so I've extracted the necessary parts for the new api-endpoint `/appVersions/id`.

feat(appversions): add endpoint for getting a single app-version

---

client/src/AppHub.js
client/src/api/index.js
client/src/pages/AppView/AppView.js
client/src/pages/AppView/AppView.module.css
client/src/pages/OrganisationView/OrganisationView.js
client/src/pages/OrganisationView/OrganisationView.module.css
client/src/pages/UserApp/DetailsCard/DetailsCard.js
client/src/pages/UserApp/DetailsCard/DetailsCard.module.css
client/src/pages/UserOrganisation/Modals/EditNameModal.js
client/src/pages/UserOrganisation/UserOrganisation.js
server/migrations/20241210123044_organisation_description.js
server/src/models/v1/out/User.js
server/src/models/v2/Organisation.js
server/src/routes/v1/apps/formatting/convertAppsToApiV1Format.js
server/src/routes/v2/organisations.js
server/src/services/organisation.js

This PR adds an organisation overview page, to support the page, it:
- extends the call to `/organisation/:id` to optionally include the apps
- adds a description field to the organisation
- only the owner of the organisation (the user who created it by default) can edit this description
- Links to the new organisation page from App pages
A followup [ticket](https://dhis2.atlassian.net/browse/HUB-161) will expose ability to filter by organisation to the app.
implements [HUB-122](https://dhis2.atlassian.net/browse/HUB-122).
[apphub-organisation-page.webm](https://github.com/user-attachments/assets/09454684-d683-4468-91de-79b374bc669d)
[HUB-122]: https://dhis2.atlassian.net/browse/HUB-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add organisation overview page

---

.platform/nginx/conf.d/client_max_body_size.conf
server/src/routes/v1/apps/handlers/createApp.js
server/src/routes/v1/apps/handlers/createAppVersion.js
server/src/routes/v2/apps.js

This increase is needed for the new version of `@dhis2/data-visualizer-app`.
In order to support client-side PDF export of charts with non-latin characters I have add a shedload of `.ttf` files to the `./public` folder. Any given user only needs one of these files and they are not downloaded until they actually use the export functionality, so the app's load-time is unaffected but the app's bundle size has exploded quite a bit. So much so that the app-hub was refusing it ([see here](https://github.com/dhis2/data-visualizer-app/actions/runs/15142637326/job/42570483879#step:7:18)) 
These changes should allow for the app to be published to app-hub successfully.

fix: increase max bundle size to 40MB

---

client/src/pages/AppView/AppView.js
client/src/pages/AppView/LatestUpdates.js
client/src/pages/UserAppEdit/DescriptionEditor.js
server/src/models/v1/out/App.js

This fix ensures that the "stable" version of an app, rather than development or canary version, is shown as the latest version to download. It also ensures that "Latest Updates" section shows the stable versions.
- In addition, it fixes an unrelated issue with the "change summary" field being mandatory when uploading a new version.
fixes https://dhis2.atlassian.net/browse/HUB-169

fix(DHIS2-19851): show "stable" version as latest version to download

---

client/src/components/Versions/Versions.js

This increases the default page size for the versions list. 
The reason is to provide a workaround for deep links to a specific version, i.e. `https://apps.dhis2.org/app/92b75fd0-34cc-451c-942f-3dd0f283bcbd?tab=previous-releases#103.1.3` which wouldn't work if the linked version is not loaded, and needs to be lazily loaded by clicking "load more". 
`50` is a bit of a random value (although `5` is very low I would say) to cater for the specific case from [Capture app](https://dhis2.slack.com/archives/C07A1DURSUA/p1756394763416269). The performance implication is minimal - if we load all releases (pageSize=1000 which loads all the 493 capture releases), which is the most extreme scenario, this makes the request ~23KB as opposed to 3KB (and it takes 170 ms as opposed to 60ms) ... I don't …

fix: change page size for versions
