packages/server/package.json
packages/server/src/main.js
packages/server/src/routes/v1/apps/formatting/convertAppsToApiV1Format.js
packages/server/src/routes/v1/apps/handlers/deleteApp.js
packages/server/src/routes/v1/apps/handlers/getAllApps.js
packages/server/src/routes/v1/apps/handlers/getMedia.js
packages/server/src/routes/v1/apps/handlers/getMyApps.js
packages/server/src/routes/v1/apps/handlers/getSingleApp.js
packages/server/src/routes/v1/apps/handlers/postApprovalStatus.js
packages/server/src/routes/v1/apps/handlers/postCreateApp.js
packages/server/src/security/auth0.js
packages/server/src/security/index.js
packages/server/src/utils/index.js
packages/server/yarn.lock

This makes it possible to run the backend without auth0 using unprotected endpoints making dev-life easier. It currently makes the app-store backend possible to run configuration-less (provided you have seeded the database)

[DHIS2-6553] optional authentication

---

README.md
package-lock.json
package.json
seeds/02_app.js
seeds/06_media.js
seeds/mock/apps.js
src/data/deleteOrganisation.js
src/main.js
test/data/index.js
test/index.js
test/routes/index.js
test/security/index.js
test/utils/index.js

Updated import paths since moduleAlias were removed, fixed so the test suite runs again.
Updated readme + some other minor refactoring

Fix broken testsuite since refactor and client/server merge

---

package.json

Should have been done in: https://github.com/dhis2/app-store/pull/108/commits/d7e4f25cd805eb87c0144c4c3838dd8e92006499 . But seems I readded the wrong joi package...

chore: move joi to normal dep

---

buildspec.yml

Now that the App is being pre-built we need to build it in
production mode during the build sequence.

ci: use production env for building the client

---

package-lock.json
package.json
src/data/getApps.js
src/routes/v1/apps/handlers/getAllApprovedApps.js
src/utils/filters.js
test/routes/index.js

feat: add dhis2 version filter support in api

---

src/data/appExists.js
src/data/createAppStatus.js
src/data/createAppVersion.js

See added comment/jsdoc in appExists.js which explains it all.

fix: allow check if app exists within transaction

---

seeds/mock/apps.js
src/plugins/apiRoutes.js
src/routes/v1/apps/handlers/createApp.js
src/routes/v1/apps/handlers/createAppVersion.js
src/routes/v1/apps/handlers/deleteApp.js
src/routes/v1/apps/handlers/deleteAppVersion.js
src/routes/v1/apps/handlers/deleteImage.js
src/routes/v1/apps/handlers/editApp.js
src/routes/v1/apps/handlers/editAppVersion.js
src/routes/v1/apps/handlers/editImage.js
src/routes/v1/apps/handlers/getAllApps.js
src/routes/v1/apps/handlers/getMyApps.js
src/routes/v1/apps/handlers/getSingleApp.js
src/routes/v1/apps/handlers/setApprovalStatus.js
src/routes/v1/apps/handlers/uploadImageToApp.js
src/routes/v2/channels.js
test/routes/index.js

... also renamed strategy from required to token to better fit into cases where it might actually be optional in combination with mode: try

fix: fixes a bug from refactoring making optional auth work for fetching a single app again

---

migrations/20191217103142_auto-uuid.js

lets see if this works on AWS, if it works we wouldnt need to enable the extension manually when spinning up new instances with fresh databases

fix: create extension if superuser

---

client/src/components/appCards/AppCardItem.jsx
client/src/components/appView/AppView.jsx
cypress/integration/app-details/index.js
cypress/integration/browse-published-apps/index.js

https://jira.dhis2.org/browse/TECH-259

refactor: replace data-test-id with data-test attributes

---

package-lock.json
package.json
src/plugins/errorMapper.js
test/plugins/errorMapper.js

feat(plugin): error-mapper

---

src/server/env-config.js
test/routes/v2/organisations.js

either this, or import the noauth-config, both works. Otherwise it will collide with local env configs

fix: make sure strategy is none for noAuth tests

---

.github/workflows/dockerpush.yml
Dockerfile

I accidentally merged an incorrect Dockerfile when squashed other commits and lost some changes.. this is the correct one that builds.

fix: correct Dockerfile so it builds

---

.dockerignore
Dockerfile

modify dockerignore due to workspace changes to include node_modules from subdirectories for example

fix: reduce docker context building locally

---

client/src/app-hub.js
client/webpack.config.js

This will make it easier to see which version is actually deployed.

feat(log): log version and build date in client console

---

client/src/components/dialog/EditAppDialog.js
client/src/components/form/EditAppForm.jsx
server/src/routes/v1/apps/handlers/createApp.js

fixes https://jira.dhis2.org/browse/HUB-80

fix: make sourceurl work when creating an app and pre-fill existing

---

client/src/components/appVersion/VersionListEdit.jsx
client/src/styles/override.css
server/src/data/createAppVersion.js
server/src/data/updateAppVersion.js
server/src/models/v1/in/CreateAppModel.js
server/src/models/v1/in/CreateAppVersionModel.js
server/src/models/v1/in/EditAppVersionModel.js
server/test/data/createAppVersion.js

https://jira.dhis2.org/browse/HUB-81

fix: demourl validation

---

server/src/utils/filters.js

resolves: https://jira.dhis2.org/browse/HUB-83

fix: use wildcard for matching patch-versions

---

client/src/components/appVersion/VersionListEdit.jsx

fixes: https://jira.dhis2.org/browse/HUB-87

fix: prevent crash when saving an unedited version

---

client/src/components/appCards/AppCards.jsx
client/src/components/appVersion/VersionItems.jsx
client/src/components/appVersion/VersionList.jsx
client/src/components/appVersion/VersionListEdit.jsx
client/src/components/dialog/DialogRoot.js
client/src/components/dialog/EditAppVersionDialog.js
client/src/components/form/EditAppVersionForm.jsx
client/src/components/form/NewAppVersionForm.jsx
client/src/components/form/UploadAppFormStepper.jsx
client/src/components/user/userAppView/UserAppView.jsx
client/src/constants/dialogTypes.js

Adds consistent Version input. Before this was free-text, but its now a Dropdown.

fix(version): use select-field when editing version

---

client/webpack.config.js

Adds the ability to import font-files.

chore(webpack): add font-files to file loader

---

client/src/constants/apiConstants.js

As far as I can tell the constants I have removed are not being used anywhere else.

refactor: remove unused API constants

---

.github/workflows/docker-publish.yml

Should remove this before we merge to prod, as this was just for testing.

chore(workflow): remove redesign-branch publish

---

client/indexbuild.html

Had forgotten to add the nested `/favicons` path.

fix(favicons): fix favicon path

---

.github/workflows/docker-publish.yml
CHANGELOG.md
client/src/lib/form-validators/index.js
client/src/lib/form-validators/name-length-validator.js
client/src/pages/UserAppEdit/UserAppEdit.js
client/src/pages/UserAppUpload/UserAppUpload.js
server/.env.template
server/src/data/createLocalizedAppVersion.js
server/src/data/getAllAppsByDeveloperId.js
server/src/data/getAllAppsByLanguage.js
server/src/data/getApps.js
server/src/data/getAppsById.js
server/src/models/v1/in/CreateAppModel.js

Resolves the merge conflict between master -> next

chore: resolve merge-conflict

---

server/src/utils/validateMime.js

Closes https://jira.dhis2.org/browse/HUB-139

fix: remove svg from list of allowed image mime types

---

client/src/pages/UserApp/VersionsCard/VersionsCard.js

Fixes [HUB-146](https://dhis2.atlassian.net/browse/HUB-146)

fix(version): close modal when deleting version

---

.platform/nginx/conf.d/client_max_body_size.conf

Fixing a regression made in https://github.com/dhis2/app-hub/pull/718
Note that the fix is already applied to apps.dhis2.org

fix: increase nginx client_max_body_size
